name: Regression

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
            use-cross: false
          - os: macOS-latest
            rust: stable
            target: x86_64-apple-darwin
            use-cross: false
          - os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            use-cross: false
#          - os: ubuntu-latest
#            rust: stable
#            target: armv7-linux-androideabi
#            use-cross: true

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use-cross }}
          command: test
          args: --locked --target ${{ matrix.target }}
      - name: Run tests feature variation
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use-cross }}
          command: test
          args: --locked --target ${{ matrix.target }} --no-default-features
